label.titulo.pagina.consulta = Exames Cadastrados
label.titulo.pagina.cadastro = Cadastro de Exame
label.titulo.pagina.edicao = Edição de Exame

label.menu.logout = Logout

label.botao.todosExames = Exames

label.incluir.nometabela = Incluir Exame
label.incluir.idexame = Código
label.incluir.nomeexame = Nome

label.editar.nometabela = Editar Exame
label.editar.idexame = Código
label.editar.nomeexame = Nome

label.salvar = Salvar
label.limpar = Limpar Formulário