label.titulo.pagina.consulta = Fichas Cadastradas
label.titulo.pagina.cadastro = Cadastro de Ficha
label.titulo.pagina.relatorioExamesRealizados = Relatório Exames Realizados
label.titulo.pagina.relatorioTopExames = Relatório Top Exames
label.titulo.pagina.edicao = Edição de Ficha

label.menu.logout = Logout

label.relatorioExamesPeriodo = REL. EXAMES PERÍODO
label.relatorioMaisRealizados = REL. TOP EXAMES

label.numeroficha = Nº Ficha
label.nomeexame = Exame
label.nomefuncionario = Funcionário
label.dataexame = Data Exame
label.idfuncionario = Código Funcionário
label.idexame = Código Exame

label.botao.todosFichas = Fichas
label.incluir.nometabela = Novo Exame do Funcionário
label.editar.nometabela = Editar Ficha do Funcionário

label.relatorio.topexames.nomerelatorio = Relatório TOP 5 Exames
label.relatorio.topexames.datainicio = Data Início
label.relatorio.topexames.datafim = Data Fim
label.relatorio.topexames.totalexames = Total Exame
label.relatorio.topexames.idexame = Código Exame
label.relatorio.topexames.nomeexame = Nome Exame

label.relatorio.examesrealizados.nomerelatorio = Relatório Exames Realizados no Período
label.relatorio.examesrealizados.datainicio = Data Início
label.relatorio.examesrealizados.datafim = Data Fim
label.relatorio.examesrealizados.idfuncionario = Código Funcionário
label.relatorio.examesrealizados.nomefuncionario = Nome Funcionário
label.relatorio.examesrealizados.idexame = Código Exame
label.relatorio.examesrealizados.nomeexame = Nome Exame
label.relatorio.examesrealizados.dataexame = Data Exame

label.salvar = Salvar
label.limpar = Limpar Formulário