label.titulo.pagina.consulta = Funcionários Cadastrados
label.titulo.pagina.cadastro = Cadastro de Funcionário
label.titulo.pagina.edicao = Edição de Funcionário

label.menu.logout = Logout

label.incluir.nometabela = Novo Funcionário
label.incluir.idfuncionario = Código
label.incluir.nomefuncionario = Nome

label.botao.todosFuncionarios = Funcionários
label.editar.nometabela = Editar Funcionário
label.editar.idfuncionario = Código
label.editar.nomefuncionario = Nome

label.salvar = Salvar
label.limpar = Limpar Formulário