label.titulo.pagina.consulta = Funcionários Cadastrados
label.titulo.pagina.cadastro = Cadastro de Funcionário
label.titulo.pagina.edicao = Edição de Funcionário
label.modal.titulo = Confirmação de Exclusão
label.modal.corpo = Deseja realizar a Exclusão do Funcionário?

label.menu.logout = Logout
label.titulo.pagina.login = Login
label.titulo.pagina.telainicial = Home

label.entrar = Entrar
label.login = Login
label.senha = Senha

label.opcao.exames = Exames
label.opcao.funcionarios = Funcionários
label.opcao.fichas = Exames Realizados (Fichas)
label.opcao.relatorioexamesrealizados = Relatório Exames Realizados no Período
label.opcao.relatoriotop5 = Relatório TOP 5 Exames